apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: spring-1811-new
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-1811-new 
  name: spring-1811-new
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: spring-1811-new 
